---
authors: 
  - 'Berke SEVİM'
  - 'Furkan PAŞAHAN'
  - 'Mert KAVAS'
  - 'Furkan ERGÜNEŞ'
date:  '`r format(Sys.Date(), "%B %Y")`'
institution: 'FEN FAKÜLTESİ'
division: 'İSTATİSTİK BÖLÜMÜ'
advisor: 'Dr. Engin YILDIZTEPE' #Danışman Ünvan Adı Soyadı
#altadvisor: 'Your Other Advisor' # Delete line if you only have one advisor
department: 'İstatistik Bölümü'
degree: 'Bitirme Projesi Raporu'  
title: 'GİYİLEBİLİR CİHAZ VE AKILLI TELEFON VERİLERİ İLE AKTİVİTE TANIMA'
knit: 'bookdown::render_book'
site: bookdown::bookdown_site

output: 
  thesisdown::thesis_pdf: default #"template.tex" şablonuna yönlendiren fonksiyon
#  thesisdown::thesis_gitbook: default
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content here or
# use code similar to line 20 for the files.  If you are producing in a different
# format than PDF, you can delete or ignore lines 20-31 in this YAML header.

abstractTR: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-ozet.Rmd", encoding="UTF-8"), collapse = '\n  ')`

abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the |.


# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is
# needed on the line after the |.



preface: |  # rapor değerlendirme
  "`r rmarkdown::metadata$title`" başlıklı bitirme projesi raporu tarafımdan okunmuş, kapsamı ve niteliği açısından bir Bitirme Projesi raporu olarak kabul edilmiştir.\
  \
  \
  `r rmarkdown::metadata$advisor`
  
acknowledgements: |
  Tüm çalışma süresince yönlendiriciliği, katkıları ve yardımları ile yanımızda olan danışmanımız `r rmarkdown::metadata$advisor` 'ye ve böyle bir çalışmayı yapmamız için bize fırsat tanıyan Dokuz Eylül Üniversitesi Fen Fakültesi İstatistik Bölümüne teşekkür ederiz.\
  \
  \
  `r rmarkdown::metadata$authors[[1]]`
  \
  `r rmarkdown::metadata$authors[[2]]`
  \
  `r rmarkdown::metadata$authors[[3]]`
  \
  `r rmarkdown::metadata$authors[[4]]`
  \
 
# ```{r, echo = FALSE,results="asis"}
# n<-length(rmarkdown::metadata$authors)
# for (i in 1:n) {
#       cat(rmarkdown::metadata$authors[[i]],sep="\n")
#   }
# ```
#

#dedication: |
#  You can have a dedication here if you wish. 
bibliography: bib/thesis.bib
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/apa-tr.csl
# Download your specific csl file and refer to it in the line above.
lot: true
lof: true
#space_between_paragraphs: true
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
 if(!require(remotes)) install.packages("remotes", repos = "http://cran.rstudio.com")
 if(!require(thesisdown))remotes::install_github("ismayc/thesisdown")
 library(thesisdown)

```

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers
on chapters.
-->

# Giriş {.unnumbered}

Günümüzde, insan aktivitelerinin otomatik olarak tanınması ve sınıflandırılması, çeşitli uygulama alanlarında büyük ilgi gören bir araştırma konusudur.Aktivite tanıma, bir kişinin yürüyüş, koşu, oturma, yatma gibi farklı aktivitelerini doğru bir şekilde tanımlayabilen ve sınıflandırabilen bir sistem oluşturmayı amaçlar.Bu alandaki gelişmeler, taşınabilir cihazların yaygınlaşması, sağlık takibi, yaşlı bakımı, spor analizi, akıllı ev sistemleri ve robotik gibi birçok uygulama alanında büyük potansiyel sunmaktadır.

Aktivite tanıma, öncelikle sensör verilerinin (jiroskop, ivmeölçer) toplanması ve işlenmesiyle gerçekleştirilir.Bu sensör verileri, bir kişinin beden hareketlerini, konumunu ve mekanda gerçekleştirdiği değişiklikleri temsil eder.Makine öğrenimi algoritmaları, bu sensör verilerini analiz ederek farklı aktiviteleri sınıflandırabilir ve tanımlayabilir.Aktivite tanıma sistemlerinin geliştirilmesiyle birlikte, sağlık takibini kolaylaştırmak ve günlük yaşam aktivitelerini daha verimli bir şekilde yöneterek yaşam kalitesini artırmak için yeni olanaklar sunulmaktadır.

Bu çalışma, aktivite tanıma konusunda yapılan araştırmaları incelemeyi ve sensör verilerini kullanarak aktivite sınıflama uygulaması geliştirmeyi amaçlamaktadır.İlk olarak Bölüm 1'de, aktivite tanımanın önemi, kullanılan sensörler ve uygulama alanları üzerinde durulmuştur.İkinci bölümde, yaygın olarak kullanılan sınıflandırma yöntemleri incelenmiştir.Bölüm 3'de sunulan uygulamada üç farklı yaklaşımda gruplanabilecek k-en yakın komşu, destek vektör makineleri, rassal ormanlar, XGBoost ve yapay sinir ağları yöntemleri kullanılmıştır.Sınıflandırma yöntemlerinin performansı tek sensörden elde edilen değişkenler ve her iki sensörden de elde edilen tüm değişkenler kullanılarak ayrı ayrı değerlendirilmiştir.Bölüm 4'de sonuçlar, farklı performans ölçütleri ile karşılaştırılmıştır.